name: example
description: Blurhash Video Example Project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: '>=1.0.0 <2.0.0'
  image_sequence_animator: '>=2.0.0 <3.0.0'
  video_player: '>=2.0.0 <3.0.0'
  path_provider: '>=2.0.0 <3.0.0'
  file_picker: '>=5.0.0 <7.0.0'
  image: '>=4.0.0 <5.0.0'
  blurhash_dart: '>=1.0.0 <2.0.0'
  ffmpeg_kit_flutter_full_gpl: '>=5.1.0 <7.0.0'
  blurhash_video: 
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: '>=2.0.0 <3.0.0'

flutter:
  uses-material-design: true
